ps dind

diff --git a/.github/workflows/github-actions-node-exporter-alpine.yml b/.github/workflows/github-actions-node-exporter-alpine.yml
--- a/.github/workflows/github-actions-node-exporter-alpine.yml
+++ b/.github/workflows/github-actions-node-exporter-alpine.yml
@@ -63,20 +63,27 @@ jobs:
       #  run: |
       #    docker inspect node-exporter
 
-      - name: Test HTTP response
-        run: |
-          CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker compose ps -q node-exporter))
-          NODE_EXPORTER_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.NODE_EXPORTER_PORT')
-          URL=http://$CONTAINER_IP:$NODE_EXPORTER_PORT
-          for i in {1..30}; do
-            if curl --silent --fail $URL > /dev/null; then
-              echo "Service is up!"
-              break
-            fi
-            echo "Waiting for Service... ($i)"
-            sleep 1
-          done
-          curl --fail $URL || (echo "Service did not respond" && exit 1)
+      #- name: Test HTTP response
+      #  run: |
+      #    CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker compose ps -q node-exporter))
+      #    NODE_EXPORTER_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.NODE_EXPORTER_PORT')
+      #    URL=http://$CONTAINER_IP:$NODE_EXPORTER_PORT
+      #    for i in {1..30}; do
+      #      if curl --silent --fail $URL > /dev/null; then
+      #        echo "Service is up!"
+      #        break
+      #      fi
+      #      echo "Waiting for Service... ($i)"
+      #      sleep 1
+      #    done
+      #    curl --fail $URL || (echo "Service did not respond" && exit 1)
 
-      - name: Tear down Docker Compose
-        run: docker compose down --volumes
+      #- name: Tear down Docker Compose
+      #  run: docker compose down --volumes
+  ping-docker-dind:
+    runs-on: ubuntu-latest
+    needs: docker-compose-test
+    steps:
+      - name: Ping Docker-in-Docker service
+        run: |
+          docker ps
