test

diff --git a/.github/workflows/github-actions-plex.yml b/.github/workflows/github-actions-plex.yml
--- a/.github/workflows/github-actions-plex.yml
+++ b/.github/workflows/github-actions-plex.yml
@@ -106,11 +106,46 @@ jobs:
         run: |
           PLEX_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.PLEX_PORT')
           URL=http://${{ env.PLEX_CONTAINER_IP }}:$PLEX_PORT/web
-          docker run --rm \
-            --network ${{ env.DOCKER_NETWORK_NAME }} \
-            --ip ${{ env.CURL_CONTAINER_IP }} \
-            curlimages/curl \
-            curl $URL
+          #!/bin/bash
+
+          MAX_RETRIES=10
+          COUNT=0
+          SUCCESS=false
+
+          while [ $COUNT -lt $MAX_RETRIES ]; do
+              echo "Attempt $((COUNT+1))..."
+              
+              docker run --rm \
+                  --network "${DOCKER_NETWORK_NAME}" \
+                  --ip "${CURL_CONTAINER_IP}" \
+                  curlimages/curl \
+                  curl "$URL"
+
+              if [ $? -eq 0 ]; then
+                  echo "Success on attempt $((COUNT+1))"
+                  SUCCESS=true
+                  break
+              fi
+
+              COUNT=$((COUNT+1))
+              sleep 10  # Optional: wait before retrying
+          done
+
+          if [ "$SUCCESS" = false ]; then
+              echo "All $MAX_RETRIES attempts failed."
+              exit 1
+          fi
+
+
+      #- name: Test HTTP response
+      #  run: |
+      #    PLEX_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.PLEX_PORT')
+      #    URL=http://${{ env.PLEX_CONTAINER_IP }}:$PLEX_PORT/web
+      #    docker run --rm \
+      #      --network ${{ env.DOCKER_NETWORK_NAME }} \
+      #      --ip ${{ env.CURL_CONTAINER_IP }} \
+      #      curlimages/curl \
+      #      curl $URL
 
       - name: Cleanup
         if: always()
